import {
  ACCESS_VERIFIED_HEADER,
  isLocalDevelopmentUrl,
  REQUEST_ORIGIN_HEADER,
  verifyCloudflareAccess,
} from './worker/access'
import { hktCalendarDate, runDueRecurringRules } from './worker/recurring'
import {
  accessFailureResponse,
  contentSecurityPolicy,
  createNonce,
  withSecurityHeaders,
} from './worker/security'

// Generated by `opennextjs-cloudflare build` before Wrangler bundles this entry.
// @ts-expect-error The generated module is intentionally absent from a clean source checkout.
import openNextWorker from './.open-next/worker.js'

const worker = {
  async fetch(request: Request, env: Env, context: ExecutionContext) {
    const nonce = createNonce()
    const policy = contentSecurityPolicy(nonce, !isLocalDevelopmentUrl(request.url))
    const access = await verifyCloudflareAccess(request, env)
    if (!access.ok) {
      return withSecurityHeaders(accessFailureResponse(access.code), request, policy)
    }

    const requestHeaders = new Headers(request.headers)
    requestHeaders.delete(ACCESS_VERIFIED_HEADER)
    requestHeaders.delete(REQUEST_ORIGIN_HEADER)
    requestHeaders.set(ACCESS_VERIFIED_HEADER, 'true')
    requestHeaders.set(REQUEST_ORIGIN_HEADER, new URL(request.url).origin)
    requestHeaders.set('Content-Security-Policy', policy)
    requestHeaders.set('x-nonce', nonce)

    const forwardedRequest = new Request(request, { headers: requestHeaders })
    const response = await openNextWorker.fetch(forwardedRequest, env, context)
    return withSecurityHeaders(response, forwardedRequest, policy)
  },

  async scheduled(controller: ScheduledController, env: Env) {
    const result = await runDueRecurringRules(env.DB, hktCalendarDate(controller.scheduledTime))
    console.info('recurring_rules_run', { trigger: 'cron', ...result })
  },
} satisfies ExportedHandler<Env>

export default worker
