import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { describe, it } from 'node:test'
import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { I18nContext, type I18nContextValue } from '../i18n/context'
import { translate } from '../i18n/core'
import { formatMoneyForDisplay } from '../lib/privacy'
import type { Account, Category, RecurringRuleCreateInput, TransactionInput } from '../lib/schema'
import { RecurringRuleDialog } from './RecurringRuleDialog'
import { TransactionDialog } from './TransactionDialog'

const accounts = [{
  id: 1,
  name: 'Wallet',
  type: 'wallet',
  currency: 'HKD',
  isActive: true,
  sortOrder: 0,
  localizationKey: null,
  openingBalanceMinor: null,
  openingBalanceOn: null,
  updatedAt: '2026-08-01T00:00:00.000Z',
}] satisfies Account[]

const categories = [{
  id: 3,
  name: 'Food',
  type: 'expense',
  icon: 'utensils',
  color: '#123456',
  isActive: true,
  sortOrder: 0,
  localizationKey: null,
  monthlyPlanMinor: null,
  updatedAt: '2026-08-01T00:00:00.000Z',
}] satisfies Category[]

const transactionDraft: TransactionInput = {
  id: '00000000-0000-4000-8000-000000000001',
  type: 'expense',
  amountMinor: 1_200,
  currency: 'HKD',
  accountId: 1,
  categoryId: 3,
  occurredOn: '2026-08-02',
  cleared: false,
  payee: 'Market',
  note: '',
}

const recurringDraft: RecurringRuleCreateInput = {
  id: '00000000-0000-4000-8000-000000000002',
  name: 'Market plan',
  type: 'expense',
  amountMinor: 1_200,
  currency: 'HKD',
  accountId: 1,
  categoryId: 3,
  frequency: 'monthly',
  scheduleStartsOn: '2026-08-02',
  scheduleEndsOn: null,
  firstOccurrenceOn: '2026-08-02',
  isActive: true,
  payee: 'Market',
  note: '',
}

const context: I18nContextValue = {
  locale: 'en',
  setLocale: () => undefined,
  ledgerCurrency: 'HKD',
  setLedgerCurrency: () => undefined,
  privacyMode: false,
  setPrivacyMode: () => undefined,
  t: (key, values) => translate('en', key, values),
  formatMoney: (minor, currency = 'HKD') => formatMoneyForDisplay(minor, currency, 'en', false),
  formatMonth: (month) => month,
  formatDate: (date) => date,
  formatNumber: String,
  localizeEntityName: (name) => name,
}

function renderTransaction(draftKind: 'duplicate' | 'ai') {
  return renderToStaticMarkup(createElement(
    I18nContext.Provider,
    { value: context },
    createElement(TransactionDialog, {
      accounts,
      categories,
      ledgerContext: 'ledger-v1',
      saving: false,
      serverError: '',
      online: true,
      source: 'live',
      transaction: null,
      draft: transactionDraft,
      draftKind,
      onClose: () => undefined,
      onSubmit: async () => true,
      onDelete: async () => true,
      onDuplicate: () => undefined,
      onMakeRecurring: () => undefined,
    }),
  ))
}

function renderRecurring(draftKind: 'manual' | 'ai') {
  return renderToStaticMarkup(createElement(
    I18nContext.Provider,
    { value: context },
    createElement(RecurringRuleDialog, {
      rule: null,
      draft: recurringDraft,
      draftKind,
      accounts,
      categories,
      ledgerContext: 'ledger-v1',
      saving: false,
      serverError: '',
      mutable: true,
      onClose: () => undefined,
      onCreate: async () => true,
      onEdit: async () => true,
    }),
  ))
}

describe('AI-generated draft dialogs', () => {
  it('distinguishes AI transaction drafts from duplicates and blocks save until reviewed', () => {
    const aiMarkup = renderTransaction('ai')
    const duplicateMarkup = renderTransaction('duplicate')

    assert.match(aiMarkup, /Review AI-generated transaction draft/)
    assert.match(aiMarkup, /This draft was generated by AI; it is not a duplicated transaction\./)
    assert.match(aiMarkup, /I reviewed this AI-generated draft and confirm its details\./)
    assert.match(aiMarkup, /button-primary save-button[^>]*disabled=""/)
    assert.match(duplicateMarkup, /Duplicate transaction/)
    assert.doesNotMatch(duplicateMarkup, /I reviewed this AI-generated draft/)
  })

  it('forces AI recurring drafts to start paused and blocks save until reviewed', () => {
    const aiMarkup = renderRecurring('ai')
    const manualMarkup = renderRecurring('manual')

    assert.match(aiMarkup, /Review AI-generated recurring draft/)
    assert.match(aiMarkup, /It starts paused and becomes active only if you explicitly enable automatic generation\./)
    assert.match(aiMarkup, /button-primary save-button[^>]*disabled=""/)
    assert.doesNotMatch(aiMarkup, /type="checkbox" checked=""/)
    assert.match(manualMarkup, /type="checkbox" checked=""/)
    assert.doesNotMatch(manualMarkup, /I reviewed this AI-generated draft/)
  })

  it('enforces acknowledgement in submit handlers and the transaction shortcut uses requestSubmit', () => {
    const transactionSource = readFileSync(new URL('./TransactionDialog.tsx', import.meta.url), 'utf8')
    const recurringSource = readFileSync(new URL('./RecurringRuleDialog.tsx', import.meta.url), 'utf8')

    assert.match(transactionSource, /if \(aiDraft && !aiDraftReviewed\) \{[\s\S]*?return/)
    assert.match(transactionSource, /requestSubmit\(saveButton\)/)
    assert.match(transactionSource, /disabled=\{busy \|\| !mutable \|\| \(aiDraft && !aiDraftReviewed\)\}/)
    assert.match(recurringSource, /if \(aiDraft && !aiDraftReviewed\) \{[\s\S]*?return/)
    assert.match(recurringSource, /disabled=\{saving \|\| !draftMutable \|\| \(aiDraft && !aiDraftReviewed\)\}/)
  })
})
